/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'ch.indiemusi.social.song'

export { $nsid }

/** A social song, that needs a groups of listeners to be fully enjoyed. */
type Main = {
  $type: 'ch.indiemusi.social.song'

  /**
   * Name of the song
   */
  name: string

  /**
   * Number of joiners needed to start the full listening experience
   */
  joinersNeeded: number
}

export type { Main }

/** A social song, that needs a groups of listeners to be fully enjoyed. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    name: l.string({ maxGraphemes: 64, maxLength: 640, minLength: 1 }),
    joinersNeeded: l.integer({ minimum: 1 }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
